import type { Expediente } from '../expediente/expediente.model';

export interface Persona {
  id: number;
  nombre: string;
  primer_apellido: string;
  segundo_apellido: string;
  fecha_nacimiento: string;
  pais_nacimiento: number;
  entidad_nacimiento: number;
  municipio_nacimiento: number;
  rfc: string;
  curp: string | null;
  estado_civil: number;
  sexo: string;
  identidad_genero: number;
  nacionalidad: number;
  escolaridad: number;
  religion: number;
  ocupacion: string[];
  otra_ocupacion: string | null;
  etnia: string | null;
  otra_etnia: string | null;
  analfabeta: string;
  indigena: string;
  lengua_indigena: string | null;
  enfermedad_mental: string;
  estatus: string;
  situacion: string;
  verificacion_identidad: string | null;
  estatus_centro: string;
  estatus_expediente: string;
  estatus_proceso: string | null;
  resumen: string | null;
  hash_dir: string | null;
  cib: string;
  tcn: string | null;
  ultimo_centro: number;
  ultimo_expediente: number;
  readonly_info: number;
  readonly_senia: number;
  readonly_biometrico: number;
  created_at: string;
  updated_at: string;
  deleted_at: string | null;
  centro_user_auth: number;
  tipo_ingreso: string;
  photo: string;
  nombre_completo: string;
  expediente: Expediente[];
}
