export interface Persona {
  _mexico: number;
  nacimiento_mexico: string;
  nacionalidad_mexicana: string;
  analfabeta: string;
  centro_user_auth: number;
  cib: string;
  curp: string | null;
  enfermedad_mental: string;
  entidad_nacimiento: number;
  escolaridad: number;
  estado_civil: number;
  estatus: string;
  estatus_centro: string;
  estatus_expediente: string;
  estatus_proceso: string;
  etnia: number;
  // expediente: any[]; // Puedes crear otra interfaz si lo necesitas tipar mejor
  fecha_nacimiento: string;
  hash_dir: string | null;
  id: number;
  identidad_genero: number;
  indigena: string;
  lengua_indigena: number;
  municipio_nacimiento: number;
  nacionalidad: number;
  nombre: string;
  nombre_completo: string;
  ocupacion: string;
  otra_etnia: string | null;
  otra_ocupacion: string | null;
  pais_nacimiento: number;
  photo: string;
  primer_apellido: string;
  readonly_biometrico: number;
  readonly_info: number;
  readonly_senia: number;
  religion: number;
  resumen: string | null;
  rfc: string | null;
  segundo_apellido: string;
  sexo: string;
  situacion: string;
  tcn: string | null;
  tipo_ingreso: string;
  ultimo_centro: number;
  ultimo_expediente: number;
  updated_at: string;
  verificacion_identidad: string | null;
}
